#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate school detail pages for manabi-note ladder."""
import os

BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # manabi-note/
TEMPLATE_PATH = os.path.join(BASE, "schools", "assets", "gen_template.html")

with open(TEMPLATE_PATH, encoding="utf-8") as f:
    TEMPLATE = f.read()

RANK_LABEL = {"s": "S", "a": "A", "b": "B", "c": "C", "d": "D"}

SCHOOLS = [
# ---------------- 公立（都立）14校 ----------------
dict(id="nishi", name="都立西高校", type_label="都立高校", rank="s", hensachi="73",
     area="杉並区", bike="18", gender="共学（男子459名・女子493名、2026年6月時点でほぼ同数）",
     official_url="https://www.metro.ed.jp/nishi-h/",
     admission_url="https://www.metro.ed.jp/nishi-h/guide/",
     clubs_url="https://www.metro.ed.jp/nishi-h/school_life/",
     photo_url="https://www.metro.ed.jp/nishi-h/our_school/",
     feature="進学指導重点校の一つで、都内トップクラスの大学合格実績を誇る自由な校風の伝統校。「文武二道」「自主自律」を教育方針に掲げ、勉強一辺倒ではなく多様な活動にのびのびと取り組むことを重視しています。",
     admission="進学指導重点校のため国語・数学・英語は独自問題（グループ作成問題）での学力検査。内申点よりも当日の学力検査の得点比重が高い入試です。募集人数・倍率は年度で変動するため公式サイトで最新の数字を確認してください。",
     clubs="50を超える部・同好会・サークルがあり、多様で活発な部活動が特徴。アメリカンフットボール部が2年連続関東大会出場するなど、複数の部が高い実績を上げています。",
     univ="東京大学・京都大学・一橋大学・東京科学大学（旧東工大）・早稲田大学・慶應義塾大学など難関国公立・私大への進学者多数。"),

dict(id="musashino-kita", name="都立武蔵野北高校", type_label="都立高校", rank="a", hensachi="65",
     area="武蔵野市", bike="13", gender="共学",
     official_url="https://www.metro.ed.jp/musashinokita-h/",
     admission_url="https://www.metro.ed.jp/musashinokita-h/guide/",
     clubs_url="https://www.metro.ed.jp/musashinokita-h/school_life/activities.html",
     photo_url="https://www.metro.ed.jp/musashinokita-h/school_life/",
     feature="1978年開校、愛称「ムサキタ」。1学年6学級・全校約700名で、武蔵野中央公園に隣接した緑豊かな環境。「文武両道」を掲げ、進学実績と部活動の両立に力を入れている中堅上位校です。台湾への修学旅行が都立高校では珍しい特徴。",
     admission="都立高校共通問題（国語・数学・英語・理科・社会の学力検査＋調査書）による一般入試が中心。学力検査と調査書の比率は7：3です。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="部活動参加率は約9割。運動部は野球・剣道・女子バレーボール・陸上競技・女子新体操など、文化部は吹奏楽・演劇・美術などが活発で、大会上位入賞を目指し熱心に活動しています。",
     univ="東京都立大学・法政大学・明治大学・青山学院大学・立教大学・成蹊大学・芝浦工業大学など、GMARCH〜中堅私大クラスへの進学が中心。"),

dict(id="toyotama", name="都立豊多摩高校", type_label="都立高校", rank="a", hensachi="64",
     area="杉並区", bike="27", gender="共学",
     official_url="https://www.metro.ed.jp/toyotama-h/",
     admission_url="https://www.metro.ed.jp/toyotama-h/guide/",
     clubs_url="https://www.metro.ed.jp/toyotama-h/school_life/activities.html",
     photo_url="https://www.metro.ed.jp/toyotama-h/school_life/",
     feature="昭和15年設立、創立80年を超える伝統校。自主自律・伸びやかな校風で知られ、制服や校則がないのが特徴です。近年、大学合格実績を伸ばしています。",
     admission="都立高校共通問題による一般入試が中心。学力検査と調査書の比率は7：3。募集人数・倍率は公式サイトの入試案内ページで最新情報を確認してください。",
     clubs="学友会（生徒会）を中心に部活動が運営され、兼部を含めると入部率は100%超。運動部16・文化部18・同好会1があり、インターハイや関東大会に出場する部もあります。",
     univ="法政大学・明治大学・学習院大学・立教大学・成蹊大学・芝浦工業大学など、GMARCH〜成成明学クラスへの進学が中心。"),

dict(id="igusa", name="都立井草高校", type_label="都立高校", rank="b", hensachi="59",
     area="練馬区", bike="12", gender="共学",
     official_url="https://www.metro.ed.jp/igusa-h/",
     admission_url="https://www.metro.ed.jp/igusa-h/guide/",
     clubs_url="https://www.metro.ed.jp/igusa-h/school_life/",
     photo_url="https://www.metro.ed.jp/igusa-h/our_school/",
     feature="練馬区上石神井に所在。「自主・自由・自律」を伝統的な教育理念に掲げ、制服や頭髪色を規定していないのが特徴。自由な校風と盛んな部活動で知られる中堅進学校です。",
     admission="都立高校共通問題による一般入試が中心。学力検査と調査書の比率は7：3。募集人数・倍率は公式サイトで確認してください。",
     clubs="ダンス部は全国大会の常連校。弓道部も盛んで、文化系では書道部が活発。都立高校では珍しいフットサル部があります。",
     univ="日本大学・東洋大学・専修大学・成蹊大学など日東駒専クラス中心。理系志望者は芝浦工業大学が届く年もあります。"),

dict(id="shakujii", name="都立石神井高校", type_label="都立高校", rank="b", hensachi="57",
     area="練馬区", bike="11", gender="共学",
     official_url="https://www.metro.ed.jp/shakujii-h/",
     admission_url="https://www.metro.ed.jp/shakujii-h/guide/guidance.html",
     clubs_url="https://www.metro.ed.jp/shakujii-h/school_life/",
     photo_url="https://www.metro.ed.jp/shakujii-h/guide/meeting.html",
     feature="「文武二道」を掲げ、学力と人間力の両立を重視。「スポーツ石神井」とも呼ばれるほど部活動が盛んで、体育祭も伝統的に盛り上がる学校です。",
     admission="都立高校共通問題による一般入試が中心。文化・スポーツ等特別推薦（サッカー・男子バスケットボール・ラグビーなど）もあります。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="部活動参加率は約9割。ソフトボール・サッカー・バスケットボール・吹奏楽が人気で、サッカー部・男子バスケットボール部・ラグビー部は関東大会出場歴もあります。",
     univ="日本大学・東洋大学・駒澤大学など日東駒専クラス中心。理系志望者は芝浦工業大学が届く年もあります。"),

dict(id="suginami", name="都立杉並高校", type_label="都立高校", rank="b", hensachi="54",
     area="杉並区", bike="28", gender="共学",
     official_url="https://www.metro.ed.jp/suginami-h/",
     admission_url="https://www.metro.ed.jp/suginami-h/guide/",
     clubs_url="https://www.metro.ed.jp/suginami-h/school_life/",
     photo_url="https://www.metro.ed.jp/suginami-h/school_life/",
     feature="「行ける学校より行きたい学校を」を掲げ、丁寧な進路指導に力を入れている学校。2年次の台湾修学旅行や、希望者向けニュージーランド語学研修（10泊11日）も特徴です。",
     admission="都立高校共通問題による一般入試が中心。学力検査と調査書の比率は7：3。募集人数・倍率は公式サイトで確認してください。",
     clubs="文化部13・運動部16があり、約7割の部に専門指導者や外部コーチが指導。吹奏楽部は全日本吹奏楽コンクール銀賞、水泳部はインターハイ連続出場の実績があります。参加率は約9割。",
     univ="日本大学25名・東洋大学17名・武蔵大学12名・工学院大学9名など（2025年3月卒実績）。"),

dict(id="hoya", name="都立保谷高校", type_label="都立高校", rank="b", hensachi="49〜57",
     area="西東京市", bike="26", gender="共学",
     official_url="https://www.metro.ed.jp/hoya-h/",
     admission_url="https://www.metro.ed.jp/hoya-h/guide/",
     clubs_url="https://www.metro.ed.jp/hoya-h/school_life/",
     photo_url="https://www.metro.ed.jp/hoya-h/news/",
     feature="1970年創立。「知性高く、人間味豊かに、心身ともに健康な人を育成する」を教育目標に、高いレベルでの文武両道を実践。2年次の修学旅行では沖縄で平和学習を行います。",
     admission="都立高校共通問題による一般入試が中心。1年次は部活動全員加入制。募集人数・倍率は公式サイトで確認してください。",
     clubs="ソフトボール部は都大会12年連続優勝の強豪。水泳部・サッカー部・硬式野球部などの運動系、吹奏楽部・演劇部・科学部・現代音楽部などの文化系も盛んです。",
     univ="東洋大学44名など日東駒専計107名、成蹊17名・武蔵21名など成成明学クラスも（2024年3月卒）。理系は芝浦工業大学クラスも視野に。"),

dict(id="suginami-sogo", name="都立杉並総合高校", type_label="都立高校（総合学科）", rank="c", hensachi="50",
     area="杉並区", bike="29", gender="共学",
     official_url="https://www.metro.ed.jp/suginamisogo-h/",
     admission_url="https://www.metro.ed.jp/suginamisogo-h/guide/",
     clubs_url="https://www.metro.ed.jp/suginamisogo-h/school_life/",
     photo_url="https://www.metro.ed.jp/suginamisogo-h/school_life/",
     feature="総合学科・単位制で、普通科目に加えて多様な選択科目から進路に合わせて学べます。キャリア教育や国際理解教育を重視し、インターンシップや海外の高校生との交流も推奨。",
     admission="総合学科のため、学力検査に加えて面接・小論文が課される入試方式（学校により異なる場合あり）。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="運動部はサッカー・テニス・バスケットボール・バレーボール・ダンス・弓道・水泳・陸上・柔道・卓球など。文化部は吹奏楽・茶道・合唱・演劇・美術・写真など選択肢が豊富です。",
     univ="大東文化大学・亜細亜大学など。専門学校・就職への進路も一定数（総合学科）。"),

dict(id="oizumi-sakura", name="都立大泉桜高校", type_label="都立高校（単位制）", rank="c", hensachi="46",
     area="練馬区", bike="35", gender="共学",
     official_url="https://www.metro.ed.jp/oizumisakura-h/",
     admission_url="https://www.metro.ed.jp/oizumisakura-h/guide/",
     clubs_url="https://www.metro.ed.jp/oizumisakura-h/school_life/activities.html",
     photo_url="https://www.metro.ed.jp/oizumisakura-h/our_school/",
     feature="単位制で美術・デザイン系の選択科目が充実しており、美大進学者が多いのが伝統。2・3年次は最大10時間まで美術科目を選択でき、6名の美術専任教員が指導にあたります。",
     admission="単位制高校のため学力検査と調査書に加え、学校により面接等が課される場合があります。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="運動部13団体・文化部16団体。全国レベルの手話部や美術部が目立ち、テニス部・剣道部・陸上競技部・ダンス部・演劇部・吹奏楽部なども活発です。",
     univ="大東文化大学・拓殖大学クラス。美術系は多摩美術大学・武蔵野美術大学など美大への進学者も伝統的に多く、専門学校・短大への進路も多い。"),

dict(id="tanashi", name="都立田無高校", type_label="都立高校", rank="c", hensachi="42〜50",
     area="西東京市", bike="29", gender="共学",
     official_url="https://www.metro.ed.jp/tanashi-h/",
     admission_url="https://www.metro.ed.jp/tanashi-h/guide/",
     clubs_url="https://www.metro.ed.jp/tanashi-h/school_life/activities.html",
     photo_url="https://www.metro.ed.jp/tanashi-h/school_life/",
     feature="部活動が盛んで、地域に根ざした落ち着いた校風の学校。文化祭・体育祭・合唱コンクールなど、クラスが一丸となって取り組む行事が充実しています。",
     admission="都立高校共通問題による一般入試が中心。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="27の部・団体があり、1年生の参加率は約8割。硬式野球・サッカー・陸上・女子ハンドボール・テニス・ダンスなどの運動系、茶道・吹奏楽・演劇・美術・科学などの文化系が活動しています。",
     univ="大東文化大学・拓殖大学クラス、専門学校への進路も。"),

dict(id="mitsugaoka", name="都立光丘高校", type_label="都立高校", rank="c", hensachi="43〜46",
     area="練馬区", bike="37", gender="共学",
     official_url="https://www.metro.ed.jp/hikarigaoka-h/",
     admission_url="https://www.metro.ed.jp/hikarigaoka-h/guide/",
     clubs_url="https://www.metro.ed.jp/hikarigaoka-h/school_life/",
     photo_url="https://www.metro.ed.jp/hikarigaoka-h/news/",
     feature="1976年開校、練馬区。個性豊かな仲間や生徒思いの先生方とのびのびと過ごせる、都立高校の中でも有数の落ち着いた雰囲気が特徴。隣接する都立光が丘公園も活用しています。",
     admission="都立高校共通問題による一般入試のほか、文化・スポーツ等特別推薦（硬式野球・男子バスケットボール・サッカー・剣道）があります。募集人数・倍率は公式サイトで確認してください。",
     clubs="都立高校の中でも特に部活動が盛んで、広いグラウンドやトレーニングルームを完備。硬式野球・男子バスケットボール・サッカー・剣道の特別推薦4部活のうち、近年3部が全国大会に出場しています。",
     univ="拓殖大学クラス、専門学校・短大への進路も多い。"),

dict(id="nogei", name="都立農芸高校", type_label="都立高校（専門学科）", rank="c", hensachi="44",
     area="杉並区", bike="13", gender="共学",
     official_url="https://www.metro.ed.jp/nogei-h/",
     admission_url="https://www.metro.ed.jp/nogei-h/guide/",
     clubs_url="https://www.metro.ed.jp/nogei-h/school_life/",
     photo_url="https://www.metro.ed.jp/nogei-h/school_life/event.html",
     feature="農業科・園芸科学科など専門学科を持つ、都内でも数少ない農業系高校。校地面積7万㎡超で、野菜圃場・施設園芸圃場・果樹園・竹林見本園など充実の施設で実習を行います。植物バイオテクノロジーの実験も。",
     admission="専門学科（園芸科学科など）のため、学力検査に加え面接や実技等が課される場合があります。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="男子バスケットボール部や植物バイオテクノロジー研究部など、学科の専門性を生かした部活動が特徴です。",
     univ="農業科・園芸科中心で東京農業大学（推薦）など農学系への進学、専門学校・就職も多い。"),

dict(id="tagara", name="都立田柄高校", type_label="都立高校", rank="d", hensachi="41〜45",
     area="練馬区", bike="39", gender="共学",
     official_url="https://www.metro.ed.jp/tagara-h/",
     admission_url="https://www.metro.ed.jp/tagara-h/guide/",
     clubs_url="https://www.metro.ed.jp/tagara-h/school_life/",
     photo_url="https://www.metro.ed.jp/tagara-h/school_life/symbols.html",
     feature="「Step forward」「Look up」「Think globally」を教育理念に、習熟度別・少人数授業を実施。都の学力向上研究校・スキルアップ推進校指定校で、少人数指導や補習体制など基礎学力の定着に力を入れています。令和2年度から制服自由選択制を導入。",
     admission="都立高校共通問題による一般入試が中心。募集人数・倍率は公式サイトの入試案内で確認してください。",
     clubs="運動系・文化系ともに明るい雰囲気の中で活動。水泳部は都大会に出場し夏期強化合宿を行うなど熱心に活動しています。",
     univ="専門学校・短大中心、大東文化大学クラスへの進学も。"),

dict(id="ogikubo", name="都立荻窪高校（定時制）", type_label="都立高校（定時制）", rank="d", hensachi="42",
     area="杉並区", bike="21", gender="共学",
     official_url="https://www.metro.ed.jp/ogikubo-he/",
     admission_url="https://www.metro.ed.jp/ogikubo-he/guide/",
     clubs_url="https://www.metro.ed.jp/ogikubo-he/school_life/activities.html",
     photo_url="https://www.metro.ed.jp/ogikubo-he/our_school/",
     notice="この学校は2007年に全日制課程が廃止され、現在は<b>定時制（三部制・単位制）</b>のみの高校です。朝（I部）・昼（II部）・夜（III部）の3つの時間帯から選んで通う仕組みで、一般的な全日制の都立高校とは入試方式・卒業までの年数の考え方（原則4年、条件を満たせば3年での卒業も可）が異なります。他校と横並びで比較する際はこの点にご注意ください。",
     feature="荻窪駅から徒歩5分の駅近校。三部制のため自分の生活リズムに合わせて登校時間を選べ、1クラスの人数が少なく手厚い指導が受けられます。「演劇入門」「アニメーション基礎」「茶道」など独自科目もあります。",
     admission="定時制のため学力検査（国語・数学・英語など）と調査書・面接による入試。全日制とは別日程・別方式での選考です。募集人数・倍率は公式サイトで確認してください。",
     clubs="2023年度は21部・4同好会が活動。バスケットボール部・バドミントン部・陸上部・自転車競技部などは全国高等学校定時制通信制体育大会に出場しています。",
     univ="卒業後の進路は専門学校・就職・大学進学など多様。定時制のため大学合格実績の公表は限定的です。"),

# ---------------- 私立22校 ----------------
dict(id="waseda-koto-gakuin", name="早稲田大学高等学院", type_label="私立高校（大学附属）", rank="s", hensachi="75",
     area="練馬区（上石神井）", bike="12", gender="男子校",
     official_url="https://www.waseda.jp/school/shs/",
     admission_url="https://www.waseda.jp/school/shs/prospective/",
     clubs_url="https://www.waseda.jp/school/shs/campus/",
     photo_url="https://www.waseda.jp/school/shs/campus/",
     feature="早稲田大学の直系附属校（男子校）。ほぼ全員が早稲田大学へ進学します。上石神井駅そばで、ご自宅から最も近い最難関附属校の一つ。大学受験に縛られない自由な学びと文武両道が特徴です。",
     admission="推薦入試と一般入試（若干名）があります。一般入試は国語・数学・英語の学力検査＋面接。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="体育系27クラブ・文化系16クラブ・同好会7・プロジェクト3が活発に活動。軟式野球部の春季都大会優勝・関東大会ベスト8、演劇部の都大会最優秀賞、吹奏楽部の都コンクール金賞など全国レベルの実績があります。",
     univ="ほぼ全員が早稲田大学へ内部推薦で進学します。"),

dict(id="waseda-jitsugyo", name="早稲田実業学校高等部", type_label="私立高校（大学系属）", rank="s", hensachi="75",
     area="国分寺市", bike="48", gender="共学（男子1,133名・女子627名＝約64:36、2024年時点）",
     official_url="https://www.wasedajg.ed.jp/",
     admission_url="https://www.wasedajg.ed.jp/admission/",
     clubs_url="https://www.wasedajg.ed.jp/schoollife/",
     photo_url="https://www.wasedajg.ed.jp/schoollife/",
     feature="1901年開校、早稲田大学の系属校。2002年度から男女共学化。附属校の中でも屈指の人気・難易度で、ほぼ全員が早稲田大学へ進学します。JR中央線・国分寺駅からバス便。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査＋面接。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="体育系25部（アイススケート・ゴルフ・山岳・弓道・少林寺拳法・スキー・ボートなど）、文化系12部（演劇・考古学・商経・吹奏楽・珠算など）、同好会15団体と幅広い選択肢があります。",
     univ="ほぼ全員が早稲田大学へ内部推薦で進学します。"),

dict(id="meiji-meiji", name="明治大学付属明治高等学校", type_label="私立高校（大学附属）", rank="s", hensachi="72",
     area="調布市", bike="36", gender="共学（男子413名・女子416名、2025年4月時点でほぼ1:1）",
     official_url="https://www.meiji.ac.jp/ko_chu/",
     admission_url="https://www.meiji.ac.jp/ko_chu/exam.html",
     clubs_url="https://www.meiji.ac.jp/ko_chu/campuslife/club.html",
     photo_url="https://www.meiji.ac.jp/ko_chu/campuslife.html",
     feature="明治大学の付属校（共学）。大半が明治大学へ内部進学し、付属校の中でも進学実績・人気ともに高い学校です。「独立自治」の精神のもと生徒主体の学校行事が特色。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="37の班・部があり、高校生の約92％がいずれかに所属。文武両道を目指し、中学では約99%、高校では約90%が部活動に参加しています。",
     univ="大半が明治大学へ内部進学します。"),

dict(id="rikkyo-niiza", name="立教新座高等学校", type_label="私立高校（大学附属）", rank="s", hensachi="71",
     area="埼玉県新座市", bike="62", gender="男子校",
     official_url="https://niiza.rikkyo.ac.jp/",
     admission_url="https://niiza.rikkyo.ac.jp/admission/",
     clubs_url="https://niiza.rikkyo.ac.jp/schoollife/",
     photo_url="https://niiza.rikkyo.ac.jp/schoollife/",
     feature="立教大学の附属校（男子校）。卒業生の約8割が推薦で立教大学へ進学します。10万㎡におよぶ緑豊かな広大なキャンパスが特徴。西武池袋線・志木駅利用で、保谷・ひばりヶ丘方面からもアクセスしやすい立地です。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査＋面接。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="体育部22・文化部18のクラブがあり、90%以上の生徒が部活動に所属しています。",
     univ="約8割が推薦で立教大学へ進学します。"),

dict(id="chuo-fuzoku", name="中央大学附属高等学校", type_label="私立高校（大学附属）", rank="a", hensachi="69",
     area="小金井市", bike="39", gender="共学",
     official_url="https://www.hs.chuo-u.ac.jp/",
     admission_url="https://www.hs.chuo-u.ac.jp/admission/",
     clubs_url="https://www.hs.chuo-u.ac.jp/schoollife/",
     photo_url="https://www.hs.chuo-u.ac.jp/schoollife/",
     feature="中央大学の附属校（共学）。中央大学杉並よりもさらに内部進学率が高い「本院系」の附属校で、JR中央線・武蔵小金井駅からアクセスできます。服装規定がなく制服もありません。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="運動部19・文化部11の計30種類。硬式野球・アメリカンフットボール・サッカー・バスケットボール・バレーボールなどの運動部、ESS・演劇・合唱・吹奏楽などの文化部があり、1年生の加入率は約80%です。",
     univ="大半が中央大学へ内部進学します。"),

dict(id="gakushuin", name="学習院高等科", type_label="私立高校", rank="a", hensachi="69",
     area="豊島区", bike="56", gender="男子校",
     official_url="https://www.gakushuin.ac.jp/bsh/",
     admission_url="https://www.gakushuin.ac.jp/bsh/admission/",
     clubs_url="https://www.gakushuin.ac.jp/bsh/",
     photo_url="https://www.gakushuin.ac.jp/bsh/",
     feature="皇室ゆかりの伝統校としても知られる男子校。「自由な校風」が特徴で髪型・髪色も自由。中等科と合同の文化祭のほか、筑波大学附属高校との総合定期戦（附属戦）、ボート大会、柔道納会、マラソン大会、北海道スキー教室など高等科独自の行事が豊富です。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査＋面接。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="運動部・文化部ともに活発で、人工芝やトレーニング場などの施設も充実。アーチェリー部や書道部は全国大会にも出場しています。",
     univ="学習院大学中心。早慶上智・GMARCHへ進む生徒も一定数います。"),

dict(id="hosei", name="法政大学高等学校", type_label="私立高校（大学附属）", rank="a", hensachi="68",
     area="三鷹市", bike="16", gender="共学（2007年男女共学化）",
     official_url="https://www.hosei.ed.jp/",
     admission_url="https://www.hosei.ed.jp/admission/",
     clubs_url="https://www.hosei.ed.jp/school/members.html",
     photo_url="https://www.hosei.ed.jp/",
     feature="法政大学の完全付属校。ほぼ全員が内部進学するため、大学受験勉強に縛られずに高校生活を送れます。2007年に三鷹市牟礼（井の頭公園・玉川上水そば）へ移転し、同時に男女共学化しました。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="文化部8・運動部16の計24部が活発に活動。ラグビー部・硬式野球部・陸上競技部などは大会やインターハイへの出場実績があります。",
     univ="ほぼ全員が法政大学へ内部進学します。"),

dict(id="nichidai-tsurugaoka", name="日本大学鶴ヶ丘高等学校", type_label="私立高校（大学附属）", rank="a", hensachi="68〜64",
     area="杉並区", bike="38", gender="共学",
     official_url="https://www.tsurugaoka.hs.nihon-u.ac.jp/",
     admission_url="https://www.tsurugaoka.hs.nihon-u.ac.jp/admission/",
     clubs_url="https://www.tsurugaoka.hs.nihon-u.ac.jp/schoollife/",
     photo_url="https://www.tsurugaoka.hs.nihon-u.ac.jp/schoollife/",
     feature="日本大学の付属校の中でも進学実績が高めで、日大への推薦資格を保持したまま他大学を受験できる制度があります。校訓は「自主創造」「真剣力行」「和衷協同」。現役進学率97.4%。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="テニス部は全国高等学校総合体育大会に出場、野球部は全国高等学校野球選手権大会に出場するなど実績豊富です。",
     univ="日本大学中心。他大学受験制度で早稲田・立教大学などGMARCH・芝浦工業大学へ進む生徒もいます。"),

dict(id="kokugakuin-kugayama", name="國學院大學久我山高等学校", type_label="私立高校（大学系属）", rank="a", hensachi="67",
     area="杉並区", bike="25", gender="共学（男子部・女子部で校舎・クラスが別、部活動と生徒会活動は男女共同）",
     official_url="https://www.kugayama-h.ed.jp/",
     admission_url="https://www.kugayama-h.ed.jp/admission/",
     clubs_url="https://www.kugayama-h.ed.jp/",
     photo_url="https://www.kugayama-h.ed.jp/",
     feature="1944年創立、2024年に80周年。男女別学（男子部・女子部）で國學院大學の系属校。文武両道を掲げ、発達段階に合わせて授業は男女別に行いつつ、部活動と生徒会活動は男女共同で実施しています。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="中高合わせて31クラブ（うち非公式2）があり、文化部が運動部より多いのが特徴。ラグビー部は全国高校ラグビー大会で5回優勝の強豪で、サッカー・野球・バスケットボール・陸上競技も全国大会常連です。",
     univ="國學院大學推薦に加え、早稲田・慶應・上智・立教大学などGMARCH・芝浦工業大学など他大学へ進む生徒も多数。"),

dict(id="nichidai-dini", name="日本大学第二高等学校", type_label="私立高校（大学附属）", rank="a", hensachi="66",
     area="杉並区", bike="25", gender="共学",
     official_url="https://www.nichidai2.ac.jp/",
     admission_url="https://www.nichidai2.ac.jp/admission/",
     clubs_url="https://www.nichidai2.ac.jp/",
     photo_url="https://www.nichidai2.ac.jp/",
     feature="日本大学の付属校で、日大への推薦進学が中心。杉並区天沼にあり、23区内最大級のキャンパスの中で生徒たちはのびのびとした学校生活を送っています。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="部活動が非常に盛んで、多くの生徒が加入。運動部・文化部ともに充実しており、全国レベルで活躍する部も少なくありません。",
     univ="日本大学中心の内部進学です。"),

dict(id="chuo-suginami", name="中央大学杉並高等学校", type_label="私立高校（大学附属）", rank="a", hensachi="65",
     area="杉並区", bike="15", gender="共学",
     official_url="https://chusugi.jp/",
     admission_url="https://chusugi.jp/admission/",
     clubs_url="https://chusugi.jp/",
     photo_url="https://chusugi.jp/",
     feature="中央大学の附属校ですが、内部推薦を保持したまま国公立大や難関私大を目指す生徒も多い「半付属」的な校風。卒業生の9割以上が中央大学へ進学。制服は文化勲章受章者・森英恵デザインのブレザー。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="文化部・運動部ともに整った施設で活動。バレーボール部は強豪で、ボート部・音楽部は全国大会レベルの実績があります。",
     univ="中央大学推薦に加え、国公立・早慶上智・立教大学・芝浦工業大学を目指す生徒も多い。"),

dict(id="seikei", name="成蹊高等学校", type_label="私立高校", rank="a", hensachi="63〜62",
     area="武蔵野市", bike="8", gender="共学",
     official_url="https://www.seikei.ac.jp/jsh/",
     admission_url="https://www.seikei.ac.jp/jsh/admission/",
     clubs_url="https://www.seikei.ac.jp/jsh/",
     photo_url="https://www.seikei.ac.jp/jsh/",
     feature="吉祥寺エリアを代表する私立校。制服がなく自由な校風で、幅広い教養を身につけるリベラルアーツを伝統としています。400mトラックやサッカー場2面など広い敷地と緑豊かな環境が特徴。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="サイクリング部やストリングス部といった珍しいクラブもあり、ほぼ全員が何かしらの部活動に参加しています。",
     univ="成蹊大学推薦に加え、早稲田・慶應・上智・立教大学などGMARCH・芝浦工業大学・国公立など進路は多岐にわたります。"),

dict(id="shotoku-gakuen", name="聖徳学園高等学校", type_label="私立高校", rank="b", hensachi="62〜57",
     area="武蔵野市", bike="25", gender="共学",
     official_url="https://jsh.shotoku.ed.jp/",
     admission_url="https://jsh.shotoku.ed.jp/admission/",
     clubs_url="https://jsh.shotoku.ed.jp/",
     photo_url="https://jsh.shotoku.ed.jp/",
     feature="「個性」「国際性」「創造性」を教育方針に掲げる武蔵野市境南町の学校。ICT教育や探究学習に力を入れており、生徒1人1台端末を早くから導入しています。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="17の部があり、男子バレーボール部は全国私立大会に7年連続出場しています。",
     univ="立教大学などGMARCH〜日東駒専クラス。ICT教育の校風もあり芝浦工業大学への進学者もいます。"),

dict(id="kosei-gakuen", name="佼成学園高等学校", type_label="私立高校", rank="b", hensachi="62〜56",
     area="杉並区", bike="41", gender="男子校",
     official_url="https://www.kosei.ac.jp/boys/",
     admission_url="https://www.kosei.ac.jp/boys/admission/",
     clubs_url="https://www.kosei.ac.jp/boys/club/",
     photo_url="https://www.kosei.ac.jp/boys/",
     feature="杉並区の男子校。特進コースを中心に難関大学への進学実績を伸ばしており、囲碁将棋部が全国トップレベルであることでも知られています。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="囲碁将棋部は文化祭で「囲碁将棋喫茶」を出店するなど活発。運動部・文化部ともに多くの部が活動しています。",
     univ="特進コースは立教大学などGMARCH〜日東駒専（芝浦工業大学クラスも含む）、その他コースは大東亜帝国クラスも。"),

dict(id="meisei-gakuen", name="明星学園高等学校", type_label="私立高校", rank="b", hensachi="56",
     area="三鷹市", bike="14", gender="共学",
     official_url="https://www.myojogakuen.ed.jp/high_school/",
     admission_url="https://www.myojogakuen.ed.jp/high_school/admission/",
     clubs_url="https://www.myojogakuen.ed.jp/high_school/school_life/club/",
     photo_url="https://www.myojogakuen.ed.jp/high_school/",
     feature="三鷹市の小規模な私立校で、小学校から高校までの12年間一貫教育。制服がなく自由でリベラルな校風で、少人数教育で一人ひとりの個性を尊重しています。単位制で、3年生は約7割が選択科目です。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査＋面接など。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="全26種類の部活動があり、サッカー・陸上・バスケットボールなどの運動部から演劇・美術・和太鼓などの文化部まで幅広く、ファッション部やサンバ部など明星学園ならではの部も。",
     univ="武蔵野美術大学・日本大学・目白大学など。早慶上理・GMARCHにも一定数進学しています。"),

dict(id="suginami-gakuin", name="杉並学院高等学校", type_label="私立高校", rank="b", hensachi="56〜52",
     area="杉並区", bike="29", gender="共学",
     official_url="https://suginami.ed.jp/",
     admission_url="https://suginami.ed.jp/admission/",
     clubs_url="https://suginami.ed.jp/",
     photo_url="https://suginami.ed.jp/",
     feature="特進・文理・普通の複数コース制で、大学進学から吹奏楽などの部活動まで幅広く対応する杉並区の私立校。教育目標は「自立、創造、調和、健康」。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="体育部16・文化部18。合唱部は国際コンクール総合優勝、バトントワーリング部・ゴルフ部は全国大会出場、剣道部は関東大会出場の実績があります。",
     univ="日東駒専〜大東亜帝国クラス。"),

dict(id="bunka-gakuen-suginami", name="文化学園大学杉並高等学校", type_label="私立高校（国際コースあり）", rank="b", hensachi="58〜51",
     area="杉並区", bike="25", gender="共学（2024年度に全学年共学化）",
     official_url="https://bunsugi.jp/",
     admission_url="https://bunsugi.jp/admission/",
     clubs_url="https://bunsugi.jp/school-life/club-senior/",
     photo_url="https://bunsugi.jp/",
     feature="国際コース（ダブルディプロマコース）ではカナダの高校卒業資格も同時取得できる日本初の制度があるなど、国際教育に力を入れています。授業は日本語・英語の両方で行われます。",
     admission="推薦入試と一般入試があります。国際コースは別途出願条件があります。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="ソフトテニス部は国体・インターハイなど全国3冠を達成、なぎなた部も全国大会に進出するなど実力派の部が揃っています。",
     univ="文化学園大学推薦のほか、国際コースは海外大学、その他は日東駒専クラスへの進学も。"),

dict(id="senshu-fuzoku", name="専修大学附属高等学校", type_label="私立高校（大学附属）", rank="b", hensachi="55",
     area="杉並区", bike="39", gender="共学（1年:男197女277、2年:男215女213、3年:男209女224＝やや女子が多い）",
     official_url="https://senshu-u-h.ed.jp/",
     admission_url="https://senshu-u-h.ed.jp/admission/",
     clubs_url="https://senshu-u-h.ed.jp/life/club/",
     photo_url="https://senshu-u-h.ed.jp/life/",
     feature="専修大学の附属校で、内部推薦資格を保持したまま他大学を受験できる体制が整っています。杉並区和泉に所在し、夏休みには希望者向けの2週間オーストラリア短期語学留学もあります。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="サッカー・野球・男子バスケットボール・ハンドボール・吹奏楽・料理部などが人数の多い部。男子バスケットボール・ダンス・ゴルフ・柔道・男女ソフトテニス・ハンドボール・陸上競技などが大会で好成績を残しています。",
     univ="専修大学中心の内部進学です。"),

dict(id="taisei", name="大成高等学校", type_label="私立高校", rank="c", hensachi="55〜47",
     area="三鷹市", bike="21", gender="共学",
     official_url="https://www.taisei.ed.jp/",
     admission_url="https://www.taisei.ed.jp/admission/",
     clubs_url="https://www.taisei.ed.jp/",
     photo_url="https://www.taisei.ed.jp/",
     feature="三鷹市の私立校で、特進・進学など複数コース制。120年以上の歴史を持つ伝統校でありながら、現代のニーズに応えるグローバル教育にも力を入れています。面倒見の良い指導で着実に学力を伸ばす校風。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="男子テニス部は全国大会常連校でダブルス全国優勝の実績あり。運動部9種類・文化部3種類が活動しています。",
     univ="帝京大学・明星大学・帝京平成大学が中心。早慶上理・GMARCHも年々増加しています。"),

dict(id="fujimura-joshi", name="藤村女子高等学校", type_label="私立高校", rank="c", hensachi="55〜44",
     area="武蔵野市", bike="8", gender="女子校",
     official_url="https://fujimura.ed.jp/",
     admission_url="https://fujimura.ed.jp/admission/",
     clubs_url="https://fujimura.ed.jp/high-school/club/",
     photo_url="https://fujimura.ed.jp/",
     feature="武蔵野市吉祥寺本町の女子校。東京女子体育大学の姉妹校で、運動系の部活動が盛んで体操系に強いのが特徴。特進・進学・スポーツなど複数コース制です。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="バドミントン・陸上・ソフトボール・バレーボール・バスケットボール・ハンドボール・硬式テニス・柔道・水泳・水球・体操・新体操・ダンス・チアなど運動部が充実。",
     univ="東洋大学・玉川大学・東京女子体育大学など。早稲田など難関大へ年10名前後の進学実績もあります。"),

dict(id="tokyo-risshou", name="東京立正高等学校", type_label="私立高校", rank="c", hensachi="52〜45",
     area="杉並区", bike="36", gender="共学（2004年に男女共学化）",
     official_url="https://www.tokyorissho.ed.jp/",
     admission_url="https://www.tokyorissho.ed.jp/exam/shs_exam.html",
     clubs_url="https://www.tokyorissho.ed.jp/schoollife/club.php",
     photo_url="https://www.tokyorissho.ed.jp/",
     feature="1927年開校、杉並区の私立校。近年は特進コースの新設などにより進学実績の向上に力を入れています。「文部両道」を掲げ、約9割の生徒が部活動に参加。",
     admission="推薦入試と一般入試があります。一般入試は国語・数学・英語の学力検査。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="鉄道研究部・吹奏楽部・ソフトテニス部など幅広い部活動があり、9月開催の「紫苑祭」は生徒会（紫友会）が中心となって企画・運営します。",
     univ="大東亜帝国クラス、専門学校への進路もあります。"),

dict(id="joshibi-fuzoku", name="女子美術大学付属高等学校", type_label="私立高校（大学付属・美術系）", rank="c", hensachi="50",
     area="杉並区", bike="40", gender="女子校",
     official_url="https://www.fuzoku.joshibi.ac.jp/",
     admission_url="https://www.fuzoku.joshibi.ac.jp/admission/",
     clubs_url="https://www.fuzoku.joshibi.ac.jp/",
     photo_url="https://www.fuzoku.joshibi.ac.jp/",
     feature="女子美術大学の付属校で、美術系の専門教育に特化した女子校。10月の創立記念日前に開催される「女子美祭」が校内最大の催しで、奈良・京都研修旅行やパリ・イタリア研修旅行など芸術に触れる行事が豊富です。",
     admission="推薦入試と一般入試があります。実技（絵画等）が課される入試方式もあります。倍率・募集人数は年度により変動するため公式サイトで確認してください。",
     clubs="運動部はバスケットボール・ワンダーフォーゲル・卓球・剣道・テニス・弓道・バトン・洋舞など。文化部は美術・絵本・クロッキー・漫画研究・イラスト研究・ファッションアート・アニメーション・管弦楽・ギターなど美術系が充実。",
     univ="女子美術大学中心（美大）への内部進学です。"),
]

def esc(s):
    return s if s else ""

count = 0
for sc in SCHOOLS:
    html = TEMPLATE
    rank_upper = RANK_LABEL[sc["rank"]]
    notice = sc.get("notice", "")
    notice_block = ""
    if notice:
        notice_block = '<div class="info-section notice"><div class="notice-box"><b>ご注意：</b>' + notice + '</div></div>'

    replacements = {
        "__NAME__": sc["name"],
        "__RANK__": sc["rank"],
        "__RANK_UPPER__": rank_upper,
        "__HENSACHI__": sc["hensachi"],
        "__TYPE_LABEL__": sc["type_label"],
        "__AREA__": sc["area"],
        "__GENDER__": sc["gender"],
        "__BIKE__": sc["bike"],
        "__OFFICIAL_URL__": sc["official_url"],
        "__ADMISSION_URL__": sc["admission_url"],
        "__CLUBS_URL__": sc["clubs_url"],
        "__PHOTO_URL__": sc["photo_url"],
        "__FEATURE__": sc["feature"],
        "__ADMISSION__": sc["admission"],
        "__CLUBS__": sc["clubs"],
        "__UNIV__": sc["univ"],
        "__NOTICE_BLOCK__": notice_block,
    }
    for k, v in replacements.items():
        html = html.replace(k, v)

    out_path = os.path.join(BASE, "schools", sc["id"] + ".html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    count += 1

print("Generated", count, "pages")
